### ISSUE TITLE
reset() function missing

### ISSUE THREAD

**Issue by MartijnWelker** [dirkgroenen/tinycon-angularjs#2]
Dear Dirk,

first of all thank you for the great wrapper, I'm currently using it in my project and came to the conclusion tinycon.reset() isn't available.

Is it possible to implement this (I tried pulling the source but when I build the files it came out completely different then the repo)

**Comment by MartijnWelker** [comment]
Update:

You can set the bubble to 0, this will clear it.

Closing the thread

**Comment by dirkgroenen** [comment]
I've added the reset method, even though it's possible to reset the favicon by setting the bubble to `0` ;)
